# Generated by Django 4.2.4 on 2023-12-03 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Product', '0002_products_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCartDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField(verbose_name='數量')),
                ('Time', models.DateTimeField(auto_now_add=True)),
                ('Price', models.IntegerField(verbose_name='價格')),
                ('Total', models.IntegerField(verbose_name='總價格')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Product.products', verbose_name='商品')),
            ],
            options={
                'verbose_name': '購物車明細',
                'verbose_name_plural': '購物車明細',
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total', models.IntegerField(verbose_name='總價格')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='類別')),
            ],
            options={
                'verbose_name': '購物車',
                'verbose_name_plural': '購物車',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateTimeField(auto_now_add=True)),
                ('Delivery_method', models.IntegerField(blank=True, choices=[(0, '自取'), (1, '寄送')], default=1, null=True, verbose_name='運送方式')),
                ('Delivery_state', models.IntegerField(blank=True, choices=[(0, '代處理'), (1, '已處理')], default=1, null=True, verbose_name='運送狀態')),
                ('Payment_method', models.IntegerField(blank=True, choices=[(0, '代處理'), (1, '已處理')], default=1, null=True, verbose_name='付款方式')),
                ('Payment_time', models.DateTimeField(blank=True, null=True, verbose_name='付款時間')),
                ('Total', models.IntegerField(verbose_name='總價格')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='類別')),
            ],
            options={
                'verbose_name': '訂單',
                'verbose_name_plural': '訂單',
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField(verbose_name='數量')),
                ('Price', models.IntegerField(verbose_name='價格')),
                ('Total', models.IntegerField(verbose_name='總價格')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Product.products', verbose_name='商品')),
            ],
            options={
                'verbose_name': '訂單明細',
                'verbose_name_plural': '訂單明細',
            },
        ),
    ]
