# Generated by Django 4.2 on 2023-12-13 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0002_restock_restockdetail_orders_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restockdetail',
            name='Branch',
        ),
        migrations.RemoveField(
            model_name='restockdetail',
            name='Product',
        ),
        migrations.RemoveField(
            model_name='restockdetail',
            name='Restock',
        ),
        migrations.RemoveField(
            model_name='restockdetail_relation',
            name='InID',
        ),
        migrations.RemoveField(
            model_name='restockdetail_relation',
            name='OutID',
        ),
        migrations.AlterModelOptions(
            name='orderlog',
            options={'verbose_name': '訂單紀錄', 'verbose_name_plural': '訂單紀錄'},
        ),
        migrations.DeleteModel(
            name='Restock',
        ),
        migrations.DeleteModel(
            name='RestockDetail',
        ),
        migrations.DeleteModel(
            name='RestockDetail_relation',
        ),
    ]
