# Generated by Django 4.2 on 2023-12-18 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0003_remove_restockdetail_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcartdetails',
            name='ShoppingCart',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='OrderManagement.shoppingcart', verbose_name='購物車'),
            preserve_default=False,
        ),
    ]
