# Generated by Django 4.2 on 2023-12-18 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0004_shoppingcartdetails_shoppingcart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcartdetails',
            name='Price',
        ),
        migrations.RemoveField(
            model_name='shoppingcartdetails',
            name='Total',
        ),
    ]
