# Generated by Django 4.2 on 2023-12-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0005_remove_shoppingcartdetails_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcartdetails',
            name='Number',
            field=models.IntegerField(blank=True, null=True, verbose_name='數量'),
        ),
    ]
