# Generated by Django 4.2 on 2023-12-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0006_alter_shoppingcartdetails_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcartdetails',
            name='Price',
            field=models.IntegerField(null=True, verbose_name='價格'),
        ),
        migrations.AddField(
            model_name='shoppingcartdetails',
            name='Total',
            field=models.IntegerField(null=True, verbose_name='總價格'),
        ),
        migrations.AlterField(
            model_name='shoppingcartdetails',
            name='Number',
            field=models.IntegerField(null=True, verbose_name='數量'),
        ),
    ]
