# Generated by Django 4.2 on 2023-12-20 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0007_shoppingcartdetails_price_shoppingcartdetails_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='Order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='OrderManagement.orders', verbose_name='訂單編號'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shoppingcartdetails',
            name='Number',
            field=models.IntegerField(blank=True, null=True, verbose_name='數量'),
        ),
    ]
