# Generated by Django 4.2 on 2023-12-21 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_alter_restock_category_alter_restock_type_and_more'),
        ('OrderManagement', '0008_orderdetails_order_alter_shoppingcartdetails_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Product.branch_inventory', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Payment_method',
            field=models.IntegerField(blank=True, choices=[(0, '親自付款'), (1, '貨到付款')], default=1, null=True, verbose_name='付款方式'),
        ),
        migrations.AlterField(
            model_name='shoppingcartdetails',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Product.branch_inventory', verbose_name='商品'),
        ),
    ]
