# Generated by Django 4.2.4 on 2023-12-24 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_alter_restock_category_alter_restock_type_and_more'),
        ('OrderManagement', '0010_rename_product_orderdetails_branch_inventory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetails',
            old_name='Branch_Inventory',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='shoppingcartdetails',
            old_name='Branch_Inventory',
            new_name='Product',
        ),
    ]
