# Generated by Django 4.2.4 on 2023-12-24 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_alter_restock_category_alter_restock_type_and_more'),
        ('OrderManagement', '0011_remove_orderdetails_branch_inventory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Product.products', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='shoppingcartdetails',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Product.products', verbose_name='商品'),
        ),
    ]
