# Generated by Django 4.2.4 on 2023-12-24 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_remove_user_address_alter_user_email_and_more'),
        ('OrderManagement', '0012_alter_orderdetails_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='member.branchs', verbose_name='店家'),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='member.branchs', verbose_name='店家'),
        ),
    ]
