# Generated by Django 4.2 on 2023-12-25 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0013_orders_branch_shoppingcart_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetails',
            old_name='Product',
            new_name='Products',
        ),
        migrations.RenameField(
            model_name='shoppingcartdetails',
            old_name='Product',
            new_name='Products',
        ),
    ]
