# Generated by Django 4.2 on 2023-12-25 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0014_rename_product_orderdetails_products_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetails',
            old_name='Products',
            new_name='Product',
        ),
    ]
