# Generated by Django 4.2.4 on 2024-01-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0016_rename_product_orderdetails_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='Delivery_method',
            field=models.IntegerField(blank=True, choices=[(0, '自取'), (1, '寄送')], default=1, null=True, verbose_name='運送方式'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='Delivery_state',
            field=models.IntegerField(blank=True, choices=[(0, '代處理'), (1, '已處理')], default=1, null=True, verbose_name='運送狀態'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='Payment_method',
            field=models.IntegerField(blank=True, choices=[(0, '親自付款'), (1, '貨到付款')], default=1, null=True, verbose_name='付款方式'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='Payment_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='付款時間'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Delivery_state',
            field=models.IntegerField(blank=True, choices=[(0, '未處理'), (1, '待出貨'), (2, '待付款'), (3, '代收貨'), (4, '完成訂單'), (5, '退貨'), (6, '退款')], default=1, null=True, verbose_name='運送狀態'),
        ),
    ]
