# Generated by Django 4.2 on 2024-02-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0017_orderdetails_delivery_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='Delivery_state',
            field=models.IntegerField(blank=True, choices=[(0, '未處理'), (1, '待出貨'), (2, '待付款'), (3, '代收貨'), (4, '完成訂單'), (5, '退貨'), (6, '退款')], default=1, null=True, verbose_name='運送狀態'),
        ),
    ]
