# Generated by Django 4.2 on 2024-02-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0019_alter_orderlog_delivery_state_alter_orderlog_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='Delivery_state',
            field=models.IntegerField(blank=True, choices=[(0, '未處理'), (1, '待出貨'), (2, '已到貨'), (3, '已釋出'), (4, '完成訂單'), (5, '退貨'), (6, '退款')], default=1, null=True, verbose_name='運送狀態'),
        ),
        migrations.AlterField(
            model_name='orderdetailslog',
            name='Delivery_state',
            field=models.IntegerField(blank=True, choices=[(0, '未處理'), (1, '待出貨'), (2, '已到貨'), (3, '已釋出'), (4, '完成訂單'), (5, '退貨'), (6, '退款')], default=1, null=True, verbose_name='運送狀態'),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='Delivery_state',
            field=models.IntegerField(blank=True, choices=[(0, '未處理'), (1, '待出貨'), (2, '已到貨'), (3, '已釋出'), (4, '完成訂單'), (5, '退貨'), (6, '退款')], default=1, null=True, verbose_name='運送狀態'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Delivery_state',
            field=models.IntegerField(blank=True, choices=[(0, '未處理'), (1, '待出貨'), (2, '已到貨'), (3, '已釋出'), (4, '完成訂單'), (5, '退貨'), (6, '退款')], default=1, null=True, verbose_name='運送狀態'),
        ),
    ]
