# Generated by Django 4.2 on 2024-02-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0020_alter_orderdetails_delivery_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='Payment_method',
            field=models.IntegerField(blank=True, choices=[(0, '現金'), (1, 'LINEPAY'), (2, '轉帳')], default=1, null=True, verbose_name='付款方式'),
        ),
    ]
