# Generated by Django 4.2.4 on 2024-02-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OrderManagement", "0021_alter_orderdetails_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderdetails",
            name="Delivery_state",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "未處理"),
                    (1, "待出貨"),
                    (2, "待付款"),
                    (3, "代收貨"),
                    (4, "完成訂單"),
                    (5, "退貨"),
                    (6, "退款"),
                ],
                default=1,
                null=True,
                verbose_name="運送狀態",
            ),
        ),
        migrations.AlterField(
            model_name="orderdetails",
            name="Payment_method",
            field=models.IntegerField(
                blank=True,
                choices=[(0, "親自付款"), (1, "貨到付款")],
                default=1,
                null=True,
                verbose_name="付款方式",
            ),
        ),
        migrations.AlterField(
            model_name="orderdetailslog",
            name="Delivery_state",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "未處理"),
                    (1, "待出貨"),
                    (2, "待付款"),
                    (3, "代收貨"),
                    (4, "完成訂單"),
                    (5, "退貨"),
                    (6, "退款"),
                ],
                default=1,
                null=True,
                verbose_name="運送狀態",
            ),
        ),
        migrations.AlterField(
            model_name="orderlog",
            name="Delivery_state",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "未處理"),
                    (1, "待出貨"),
                    (2, "待付款"),
                    (3, "代收貨"),
                    (4, "完成訂單"),
                    (5, "退貨"),
                    (6, "退款"),
                ],
                default=1,
                null=True,
                verbose_name="運送狀態",
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="Delivery_state",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "未處理"),
                    (1, "待出貨"),
                    (2, "待付款"),
                    (3, "代收貨"),
                    (4, "完成訂單"),
                    (5, "退貨"),
                    (6, "退款"),
                ],
                default=1,
                null=True,
                verbose_name="運送狀態",
            ),
        ),
    ]
