# Generated by Django 5.0.6 on 2024-06-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0022_alter_orderdetails_delivery_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='Delivery_state',
            field=models.IntegerField(blank=True, choices=[(0, '未處理'), (1, '待出貨'), (2, '已到貨'), (3, '已釋出'), (4, '完成訂單'), (5, '退貨'), (6, '退款')], default=1, null=True, verbose_name='運送狀態'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='Payment_method',
            field=models.IntegerField(blank=True, choices=[(0, '現金'), (1, 'LINEPAY'), (2, '轉帳')], default=1, null=True, verbose_name='付款方式'),
        ),
        migrations.AlterField(
            model_name='orderdetailslog',
            name='Delivery_state',
            field=models.IntegerField(blank=True, choices=[(0, '未處理'), (1, '待出貨'), (2, '已到貨'), (3, '已釋出'), (4, '完成訂單'), (5, '退貨'), (6, '退款')], default=1, null=True, verbose_name='運送狀態'),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='Delivery_state',
            field=models.IntegerField(blank=True, choices=[(0, '未處理'), (1, '待出貨'), (2, '已到貨'), (3, '已釋出'), (4, '完成訂單'), (5, '退貨'), (6, '退款')], default=1, null=True, verbose_name='運送狀態'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Delivery_state',
            field=models.IntegerField(blank=True, choices=[(0, '未處理'), (1, '待出貨'), (2, '已到貨'), (3, '已釋出'), (4, '完成訂單'), (5, '退貨'), (6, '退款')], default=1, null=True, verbose_name='運送狀態'),
        ),
    ]
