# Generated by Django 4.2.4 on 2023-12-03 11:40

import Product.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=99, verbose_name='類別名稱')),
                ('Describe', models.CharField(max_length=99, verbose_name='類別描述')),
            ],
            options={
                'verbose_name': '類別管理',
                'verbose_name_plural': '類別管理',
            },
        ),
        migrations.CreateModel(
            name='Products_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_name', models.CharField(blank=True, max_length=99, null=True, verbose_name='貨品名稱')),
                ('Price', models.IntegerField(verbose_name='建議售價')),
                ('Specification', models.CharField(max_length=99, verbose_name='規格')),
                ('Number', models.IntegerField(verbose_name='庫存')),
                ('Sh', models.IntegerField(choices=[(0, '下架'), (1, '上架')], default=1, verbose_name='上/下架')),
                ('Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.categories', verbose_name='類別')),
            ],
            options={
                'verbose_name': '商品管理',
                'verbose_name_plural': '商品管理',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExpiryDate', models.DateTimeField(verbose_name='有效日期')),
                ('Number', models.IntegerField(verbose_name='數量')),
                ('Product_list', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Product.products_list', verbose_name='商品')),
            ],
            options={
                'verbose_name': '進貨商品管理',
                'verbose_name_plural': '進貨商品管理',
            },
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('ImageID', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='會員編號')),
                ('Image_path', models.ImageField(upload_to=Product.models.UploadToPathAndRename('image/productimage/'), verbose_name='商品圖片')),
                ('Product_list', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Product.products_list', verbose_name='商品')),
            ],
            options={
                'verbose_name': '圖片管理',
                'verbose_name_plural': '圖片管理',
            },
        ),
    ]
