# Generated by Django 4.2.4 on 2023-12-03 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_branchs_remove_user_branch_id_alter_user_is_active_and_more'),
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Branch',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='member.branchs', verbose_name='店家'),
            preserve_default=False,
        ),
    ]
