# Generated by Django 4.2.4 on 2023-12-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_alter_restock_category_alter_restock_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restockdetail',
            name='Remain',
            field=models.IntegerField(blank=True, null=True, verbose_name='剩餘數量'),
        ),
    ]
