# Generated by Django 4.2.4 on 2023-12-16 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('Product', '0007_alter_restockdetail_remain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restock',
            name='Category',
            field=models.IntegerField(blank=True, choices=[(0, '進貨'), (1, 'BtoB'), (2, 'BtoC')], default=1, null=True, verbose_name='進貨狀態'),
        ),
        migrations.AlterField(
            model_name='restock',
            name='Type',
            field=models.IntegerField(blank=True, choices=[(0, '進貨'), (1, '出貨')], default=1, null=True, verbose_name='進出貨'),
        ),
        migrations.AlterField(
            model_name='restock',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='分店/訂單'),
        ),
        migrations.AlterField(
            model_name='restock',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='分店/訂單的ID'),
        ),
    ]
