# Generated by Django 4.2 on 2023-12-25 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_alter_restock_category_alter_restock_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch_inventory',
            name='Products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='inventory_records', to='Product.products', verbose_name='商品'),
        ),
    ]
