# Generated by Django 4.2.4 on 2024-01-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0010_alter_restockdetail_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Import_price',
            field=models.IntegerField(default=50, verbose_name='成本價'),
            preserve_default=False,
        ),
    ]
