# Generated by Django 4.2.4 on 2024-01-02 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0011_products_import_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='Number',
        ),
    ]
