# Generated by Django 4.2.4 on 2024-01-05 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0013_alter_restock_category'),
        ('Product', '0013_alter_restockdetail_restock'),
    ]

    operations = [
    ]
