# Generated by Django 4.2.4 on 2024-01-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0014_merge_20240105_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Specification',
            field=models.CharField(blank=True, max_length=99, null=True, verbose_name='規格'),
        ),
    ]
