# Generated by Django 4.2.4 on 2024-02-02 16:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0017_alter_branch_inventory_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='restockdetail',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
