# Generated by Django 4.2.4 on 2024-02-02 16:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0018_restockdetail_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restockdetail',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='restockdetail',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
