# Generated by Django 4.2.4 on 2024-02-02 16:46

import Product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0019_remove_restockdetail_uuid_alter_restockdetail_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restockdetail',
            name='id',
            field=models.UUIDField(default=Product.models.gen_RestockDetail_id, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
