# Generated by Django 4.2.4 on 2024-02-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0021_alter_restockdetail_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='Import_price',
        ),
        migrations.AddField(
            model_name='restockdetail',
            name='Import_price',
            field=models.IntegerField(default=0, verbose_name='成本價'),
            preserve_default=False,
        ),
    ]
