# Generated by Django 4.2.4 on 2024-02-04 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0023_alter_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='Products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.products', verbose_name='商品'),
        ),
    ]
