# Generated by Django 4.2.4 on 2024-02-05 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0026_transpose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transpose',
            name='Restock',
        ),
    ]
