# Generated by Django 4.2.4 on 2024-02-05 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0028_transpose_restock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transpose',
        ),
    ]
