# Generated by Django 4.2.4 on 2024-02-05 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('member', '0013_delete_transpose'),
        ('Product', '0029_delete_transpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateTimeField(auto_now_add=True)),
                ('BranchsReceipt', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='receipt_transposes', to='member.branchs', verbose_name='收獲方')),
                ('BranchsSend', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='send_transposes', to='member.branchs', verbose_name='寄送方')),
                ('User', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='會員')),
            ],
            options={
                'verbose_name': '運送',
                'verbose_name_plural': '運送',
            },
        ),
    ]
