# Generated by Django 5.0.6 on 2024-06-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0031_transpose_restock'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='Category_images',
            field=models.IntegerField(choices=[(0, 'maet'), (1, 'fish'), (2, 'other'), (3, 'soldout'), (4, 'vegetable')], default=1, verbose_name='類別圖片'),
        ),
    ]
