# Generated by Django 5.0.6 on 2024-06-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0032_categories_category_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='Describe',
            field=models.CharField(blank=True, max_length=99, null=True, verbose_name='類別描述'),
        ),
    ]
