# Generated by Django 4.2.4 on 2024-06-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0034_alter_categories_category_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='Category_images',
            field=models.IntegerField(choices=[(0, 'meat'), (1, 'fish'), (2, 'other'), (3, 'soldout'), (4, 'vegetable')], default=2, verbose_name='類別圖片'),
        ),
    ]
