# Generated by Django 4.2.4 on 2023-12-03 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branchs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=15, verbose_name='店家名稱')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='branch_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='啟動帳戶'),
        ),
        migrations.CreateModel(
            name='Transpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField(verbose_name='數量')),
                ('Time', models.DateTimeField(auto_now_add=True)),
                ('BranchsReceipt', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='receipt_transposes', to='member.branchs', verbose_name='收獲方')),
                ('BranchsSend', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='send_transposes', to='member.branchs', verbose_name='寄送方')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Product.products', verbose_name='商品')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='member.branchs', verbose_name='店家'),
            preserve_default=False,
        ),
    ]
