# Generated by Django 4.2.4 on 2023-12-03 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_alter_user_branch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branchs',
            options={'verbose_name': '店家', 'verbose_name_plural': '店家'},
        ),
        migrations.AlterModelOptions(
            name='transpose',
            options={'verbose_name': '運送', 'verbose_name_plural': '運送'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '帳號', 'verbose_name_plural': '帳號'},
        ),
    ]
