# Generated by Django 4.2.4 on 2023-12-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_alter_branchs_options_alter_transpose_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchs',
            name='phone_number',
            field=models.CharField(default=0, max_length=15, verbose_name='店家電話'),
            preserve_default=False,
        ),
    ]
