# Generated by Django 4.2 on 2023-12-28 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_remove_user_address_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transpose',
            name='User',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='會員'),
        ),
    ]
