# Generated by Django 4.2.4 on 2024-01-05 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_transpose_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transpose',
            name='Number',
        ),
        migrations.RemoveField(
            model_name='transpose',
            name='Product',
        ),
    ]
