# Generated by Django 4.2.4 on 2024-02-05 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_remove_transpose_number_remove_transpose_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transpose',
        ),
    ]
