# Generated by Django 4.2.4 on 2024-02-05 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0012_transpose'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transpose',
        ),
    ]
