# Generated by Django 4.2.4 on 2024-07-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0013_delete_transpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='LINE_token',
            field=models.CharField(default=1, max_length=512, verbose_name='LINE token'),
            preserve_default=False,
        ),
    ]
