# Generated by Django 4.2.4 on 2024-07-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0014_user_line_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='LINE_access_token',
            field=models.CharField(default=0, max_length=512, verbose_name='LINE access token'),
            preserve_default=False,
        ),
    ]
