# Generated by Django 4.2.4 on 2024-07-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0015_user_line_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='LINE_access_token',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='LINE access token'),
        ),
    ]
